name: ahmedlb_tenis_flutter_marcador_proyecto
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  go_router: ^17.0.1
  google_fonts: ^6.3.3
  http: ^1.6.0
  provider: ^6.1.5+1
  renderer: ^0.0.19

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
